import { createSlice } from '@reduxjs/toolkit';
import {
  flashButton,
  playSound,
  keyLookup
} from './drumFunctions'

const initialState = {
  power: 1,
  volume: 100,
  track: 'A',
  text: ''
};

export const drumSlice = createSlice({
  name: 'drum',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    pressKey: (state, action) => {
      const keyPressed = action.payload;
      if(state.power) {
        // play flash animation
        // TODO
        flashButton(keyPressed)
        // play sound
        // TODO
        const mp3FN = keyPressed + '_' + state.track + '.mp3'
        playSound(mp3FN, state.volume)
        // update text box
        state.text = keyLookup(keyPressed, state.track)
      }
    },

    flipPower: (state, action) => {
      // I know this is terrible for a redux app, but this is in createSlice so it's okay
      state.power = !state.power
    },

    flipTrack: (state, action) => {
      state.track = (state.track === 'A')
        ? 'B'
        : 'A'
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: ,
});

export const { pressKey, flipPower, flipTrack } = drumSlice.actions;

export default drumSlice.reducer;
